apiVersion: v1
kind: Service
metadata:
  name: ranger-solr
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: ranger-solr
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983